# Generated by Django 4.1.5 on 2023-01-26 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_matricula'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matricula',
            old_name='aluno',
            new_name='Aluno',
        ),
        migrations.RenameField(
            model_name='matricula',
            old_name='curso',
            new_name='Curso',
        ),
    ]
